import express from 'express';import cors from 'cors';import rateLimit from 'express-rate-limit';import multer from 'multer';import nodemailer from 'nodemailer';import twilio from 'twilio';import {fileURLToPath} from 'node:url';
const LIMITS={name:100,phone:30,email:254,project_type:30,service:60,paint_area:200,project_size:200,surface_condition:100,prep_concerns:500,timing:100,preferred_contact:30,description:1000,additional_details:1000,selected_color:100,surface_description:200,lead_source:80};
const allowedTypes=new Set(['image/jpeg','image/png','image/webp']);
const clean=v=>String(v??'').trim();const tooLong=b=>Object.entries(LIMITS).some(([k,n])=>clean(b[k]).length>n);const esc=s=>clean(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export function normalize(body={}){const lead={};for(const [key,max] of Object.entries(LIMITS))lead[key]=clean(body[key]).slice(0,max);lead.project_type=lead.project_type||clean(body.project);lead.description=lead.description||clean(body.project_description).slice(0,LIMITS.description);return lead}
function validate(l){if(!l.name||!l.phone||!l.email||!l.project_type||!l.service)return false;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(l.email))return false;if(!/^[+()\d .-]{7,30}$/.test(l.phone)||l.phone.replace(/\D/g,'').length<7)return false;return Object.entries(LIMITS).every(([k,n])=>clean(l[k]).length<=n)}
const labels={name:'CUSTOMER',phone:'PHONE',email:'EMAIL',service:'SERVICE',lead_source:'LEAD SOURCE',project_type:'PROJECT TYPE',paint_area:'PAINT AREA',project_size:'PROJECT SIZE',surface_condition:'SURFACE CONDITION',prep_concerns:'PREP CONCERNS',timing:'TIMING',preferred_contact:'PREFERRED CONTACT',description:'DESCRIPTION',additional_details:'ADDITIONAL DETAILS',selected_color:'SELECTED COLOR',surface_description:'SURFACE DESCRIPTION'};
export function buildMail(l,file,env){const order=Object.keys(labels),rows=order.filter(k=>l[k]).map(k=>`${labels[k]}\n${l[k]}`);if(file)rows.push('COLOR STUDIO PREVIEW\nAttached');const text=rows.join('\n\n');const html=`<!doctype html><html><body style="margin:0;background:#eee9e1;font-family:Arial,sans-serif;color:#211f1c"><div style="max-width:600px;margin:auto;background:#fff"><div style="background:#201f1d;color:#fff;padding:22px"><b style="color:#dc655b">NEW CIMO LEAD</b><h1 style="font-size:22px;margin:8px 0 0">${esc(l.service)} — ${esc(l.project_type)}</h1></div><div style="padding:22px">${order.filter(k=>l[k]).map(k=>`<div style="border-bottom:1px solid #ddd;padding:10px 0"><b style="font-size:11px;color:#913b33">${labels[k]}</b><div style="font-size:17px;margin-top:4px;overflow-wrap:anywhere">${esc(l[k])}</div></div>`).join('')}${file?'<div style="padding:12px 0"><b>COLOR STUDIO PREVIEW</b><br>Attached</div>':''}</div></div></body></html>`;return{from:`Cimo Website Leads <${env.GMAIL_USER}>`,to:env.LEAD_EMAIL_TO,replyTo:l.email,subject:`New Cimo Lead — ${l.service} — ${l.project_type}`,text,html,attachments:file?[{filename:'cimo-color-preview.jpg',content:file.buffer,contentType:file.mimetype}]:[]}}
export function createApp({env=process.env,transporter,smsClient}={}){const app=express();app.set('trust proxy',1);const origins=clean(env.ALLOWED_ORIGINS).split(',').map(x=>x.trim()).filter(Boolean);app.use(cors({origin(origin,cb){if(!origin||origins.includes(origin))return cb(null,true);cb(new Error('origin'))},methods:['POST','OPTIONS']}));app.use(rateLimit({windowMs:15*60*1000,limit:Number(env.RATE_LIMIT||10),standardHeaders:true,legacyHeaders:false}));app.get('/health',(_q,r)=>r.json({ok:true}));const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1,fields:25,fieldSize:12000},fileFilter(_q,f,cb){allowedTypes.has(f.mimetype)?cb(null,true):cb(new multer.MulterError('LIMIT_UNEXPECTED_FILE','preview'))}}).single('preview');app.post('/api/contact',(req,res)=>upload(req,res,async err=>{if(err)return res.status(400).json({error:'Invalid request'});try{if(clean(req.body.website))return res.status(400).json({error:'Invalid request'});if(tooLong(req.body))return res.status(400).json({error:'Please check the required fields'});const lead=normalize(req.body);if(!validate(lead))return res.status(400).json({error:'Please check the required fields'});const mailer=transporter||nodemailer.createTransport({service:'gmail',auth:{user:env.GMAIL_USER,pass:env.GMAIL_APP_PASSWORD}});await mailer.sendMail(buildMail(lead,req.file,env));if(clean(env.SMS_ENABLED).toLowerCase()==='true'){try{const sms=smsClient||twilio(env.TWILIO_ACCOUNT_SID,env.TWILIO_AUTH_TOKEN);await sms.messages.create({to:env.SMS_TO,from:env.TWILIO_FROM,body:`Cimo lead: ${lead.name} — ${lead.service}. Check email for details. Customer: ${lead.phone}`})}catch{console.warn('Optional SMS alert failed')}}return res.status(202).json({ok:true})}catch{console.error('Lead email delivery failed');return res.status(502).json({error:'Unable to send request'})}}));app.use((err,_q,res,_n)=>res.status(err.message==='origin'?403:400).json({error:'Invalid request'}));return app}
const isMain=process.argv[1]===fileURLToPath(import.meta.url);if(isMain){const port=process.env.PORT||3000;createApp().listen(port,'0.0.0.0',()=>console.log(`Cimo Lead API listening on ${port}`))}
