import test from 'node:test';import assert from 'node:assert/strict';import request from 'supertest';import {createApp,normalize} from '../src.js';
const env={GMAIL_USER:'sender@example.test',LEAD_EMAIL_TO:'recipient@example.test',ALLOWED_ORIGINS:'https://jderomanis1.github.io',SMS_ENABLED:'false'};
const valid={name:'Jane Smith',phone:'585-555-1234',email:'jane@example.com',project_type:'Residential',service:'Interior Painting',paint_area:'Living room',project_size:'One room',surface_condition:'Good',timing:'Within one month',preferred_contact:'Email'};
function setup(extra={}){const sent=[];const transporter={sendMail:async m=>{if(extra.smtpFail)throw Error('smtp');sent.push(m)}};const smsClient={messages:{create:extra.smsFail?async()=>{throw Error('sms')}:async()=>({sid:'mock'})}};return{app:createApp({env:{...env,...extra.env},transporter,smsClient}),sent}}
test('normalizes legacy project fields',()=>{const l=normalize({project:'Residential',project_description:'Two rooms'});assert.equal(l.project_type,'Residential');assert.equal(l.description,'Two rooms')});
test('standard estimate, subject, Reply-To, no secrets',async()=>{const {app,sent}=setup();await request(app).post('/api/contact').set('Origin',env.ALLOWED_ORIGINS).field(valid).expect(202);assert.equal(sent[0].replyTo,valid.email);assert.equal(sent[0].subject,'New Cimo Lead — Interior Painting — Residential');assert.equal(sent[0].from,'Cimo Website Leads <sender@example.test>');assert.doesNotMatch(sent[0].text,/GMAIL|password/i)});
test('one image accepted and attached from memory',async()=>{const {app,sent}=setup();await request(app).post('/api/contact').field(valid).attach('preview',Buffer.from([0xff,0xd8,0xff]),{filename:'x.jpg',contentType:'image/jpeg'}).expect(202);assert.equal(sent[0].attachments.length,1);assert.equal(sent[0].attachments[0].filename,'cimo-color-preview.jpg')});
test('second image rejected',async()=>{const {app}=setup();await request(app).post('/api/contact').field(valid).attach('preview',Buffer.from('a'),{filename:'a.jpg',contentType:'image/jpeg'}).attach('preview',Buffer.from('b'),{filename:'b.jpg',contentType:'image/jpeg'}).expect(400)});
test('invalid MIME and oversized image rejected',async()=>{const {app}=setup();await request(app).post('/api/contact').field(valid).attach('preview',Buffer.from('x'),{filename:'x.txt',contentType:'text/plain'}).expect(400);await request(app).post('/api/contact').field(valid).attach('preview',Buffer.alloc(5*1024*1024+1),{filename:'x.jpg',contentType:'image/jpeg'}).expect(400)});
test('required fields, malformed email, malformed phone, honeypot',async()=>{const {app}=setup();await request(app).post('/api/contact').field({...valid,name:''}).expect(400);await request(app).post('/api/contact').field({...valid,email:'bad'}).expect(400);await request(app).post('/api/contact').field({...valid,phone:'abc'}).expect(400);await request(app).post('/api/contact').field({...valid,website:'bot'}).expect(400)});
test('origin rejected',async()=>{const {app}=setup();await request(app).post('/api/contact').set('Origin','https://evil.test').field(valid).expect(403)});
test('SMTP failure is generic',async()=>{const {app}=setup({smtpFail:true});const r=await request(app).post('/api/contact').field(valid).expect(502);assert.deepEqual(r.body,{error:'Unable to send request'})});
test('SMS failure does not fail delivered email',async()=>{const {app,sent}=setup({env:{SMS_ENABLED:'true',SMS_TO:'+15855550000',TWILIO_FROM:'+15855550001'},smsFail:true});await request(app).post('/api/contact').field(valid).expect(202);assert.equal(sent.length,1)});
test('rate limit rejects excess requests',async()=>{const {app}=setup({env:{RATE_LIMIT:'1'}});await request(app).post('/api/contact').field(valid).expect(202);await request(app).post('/api/contact').field(valid).expect(429)});
